# Pandas
pandas DataFrame

Pandas Series

Pandas Basic Operation

In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [3]:
#creating a data frame
pd.DataFrame(data=np.arange(0,20).reshape(5,4),
             index=['Rows1','Rows2','Rows3','Rows4','Rows5'],
             columns=["Column1","Column2","Column3","Column4"])

Column1  Column2  Column3  Column4
Rows1        0        1        2        3
Rows2        4        5        6        7
Rows3        8        9       10       11
Rows4       12       13       14       15
Rows5       16       17       18       19

In [4]:
df = pd.DataFrame(data=np.arange(0,50).reshape(5,10),
            index = ['Row1','Row2','Row3','Row4','Row5'],
            columns = ['column1','column2','column3','column4','column5','column6','column7','column8','column9','column10'])


In [5]:
df

column1  column2  column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   
Row3       20       21       22       23       24       25       26       27   
Row4       30       31       32       33       34       35       36       37   
Row5       40       41       42       43       44       45       46       47   

      column9  column10  
Row1        8         9  
Row2       18        19  
Row3       28        29  
Row4       38        39  
Row5       48        49

In [6]:
df.head(2)

column1  column2  column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   

      column9  column10  
Row1        8         9  
Row2       18        19

In [7]:
df.tail(2)

column1  column2  column3  column4  column5  column6  column7  column8  \
Row4       30       31       32       33       34       35       36       37   
Row5       40       41       42       43       44       45       46       47   

      column9  column10  
Row4       38        39  
Row5       48        49

In [8]:
df.describe()

column1    column2    column3    column4    column5    column6  \
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   
mean   20.000000  21.000000  22.000000  23.000000  24.000000  25.000000   
std    15.811388  15.811388  15.811388  15.811388  15.811388  15.811388   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    10.000000  11.000000  12.000000  13.000000  14.000000  15.000000   
50%    20.000000  21.000000  22.000000  23.000000  24.000000  25.000000   
75%    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000   
max    40.000000  41.000000  42.000000  43.000000  44.000000  45.000000   

         column7    column8    column9   column10  
count   5.000000   5.000000   5.000000   5.000000  
mean   26.000000  27.000000  28.000000  29.000000  
std    15.811388  15.811388  15.811388  15.811388  
min     6.000000   7.000000   8.000000   9.000000  
25%    16.000000  17.000000  18.000000  19.000000  
50%    26.000000  27.000000  28.000000  29.000000  
75%    36.000000  37.000000  38.000000  39.000000  
max    46.000000  47.000000  48.000000  49.000000

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df[['column1','column4','column5']]

column1  column4  column5
Row1        0        3        4
Row2       10       13       14
Row3       20       23       24
Row4       30       33       34
Row5       40       43       44

In [11]:
df

column1  column2  column3  column4  column5  column6  column7  column8  \
Row1        0        1        2        3        4        5        6        7   
Row2       10       11       12       13       14       15       16       17   
Row3       20       21       22       23       24       25       26       27   
Row4       30       31       32       33       34       35       36       37   
Row5       40       41       42       43       44       45       46       47   

      column9  column10  
Row1        8         9  
Row2       18        19  
Row3       28        29  
Row4       38        39  
Row5       48        49

In [12]:
df.iloc[0:4,3:6]

column4  column5  column6
Row1        3        4        5
Row2       13       14       15
Row3       23       24       25
Row4       33       34       35

In [13]:
df.iloc[0:4,3:6].values

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [14]:
np.nan

nan

In [15]:
pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],
             index=["Row1", "Row2","Row3"],
            columns=['Column1','Column2','Column3'])


Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4
Row3        5      4.0        3

In [17]:
df = pd.DataFrame(data=[[1,np.nan,3],[1,3,4],[5,7,3]],
            index=['Row1','Row2','Row3'],
            columns=['Column1','Column2','Column3'])

In [18]:
df

Column1  Column2  Column3
Row1        1      NaN        3
Row2        1      3.0        4
Row3        5      7.0        3

In [19]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False
Row3    False    False    False

In [20]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [21]:
df.isna().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [22]:
df

Column1  Column2  Column3
Row1        1      NaN        3
Row2        1      3.0        4
Row3        5      7.0        3

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Row1 to Row3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Column1  3 non-null      int64  
 1   Column2  2 non-null      float64
 2   Column3  3 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 96.0+ bytes


In [ ]:
# values counts in series

In [24]:
df['Column1'].unique()

array([1, 5], dtype=int64)

In [25]:
df['Column1'].nunique()

2

In [28]:
fd = pd.DataFrame({'A':[1,2,3], 'B':[1,3,4]})

In [29]:
fd

A  B
0  1  1
1  2  3
2  3  4

In [30]:
fd['B'].unique

<bound method Series.unique of 0    1
1    3
2    4
Name: B, dtype: int64>

In [31]:
fd.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [ ]:
#Creating a dataframe

In [34]:
dff = pd.DataFrame(data = np.arange(0,20).reshape(4,5),
            index = ['row1','row2','row3','row4'],
            columns = ['column1','column2','column3','column4','column5'])

In [38]:
dff[dff['column2']>10]

column1  column2  column3  column4  column5
row3       10       11       12       13       14
row4       15       16       17       18       19

In [39]:
dff[dff.isnull()]

column1  column2  column3  column4  column5
row1      NaN      NaN      NaN      NaN      NaN
row2      NaN      NaN      NaN      NaN      NaN
row3      NaN      NaN      NaN      NaN      NaN
row4      NaN      NaN      NaN      NaN      NaN

In [44]:
dff.head(3)

column1  column2  column3  column4  column5
row1        0        1        2        3        4
row2        5        6        7        8        9
row3       10       11       12       13       14

In [46]:
dff.to_csv('test.csv',index=False)

In [47]:
pd.read_csv('test.csv')

column1  column2  column3  column4  column5
0        0        1        2        3        4
1        5        6        7        8        9
2       10       11       12       13       14
3       15       16       17       18       19

In [48]:
data='{"employee_name":"Krish","email":"Krish@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [49]:
data

'{"employee_name":"Krish","email":"Krish@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [50]:
type(data)

str

In [51]:
df2=pd.read_json(data)

In [52]:
df2

employee_name            email                                  job_profile
0         Krish  Krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [53]:
df2['salary'] = 100

In [54]:
df2

employee_name            email                                  job_profile  \
0         Krish  Krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}   

   salary  
0     100

In [55]:
dict(df2['job_profile'])[0]['role']

'Developer'

In [56]:
data

'{"employee_name":"Krish","email":"Krish@gmail.com","job_profile":[{"title":"Team Lead","role":"Developer"}]}'

In [57]:
pd.read_json(data,orient='record')

employee_name            email                                  job_profile
0         Krish  Krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [58]:
pd.read_json(data,orient='index')

0
employee_name                                          Krish
email                                        Krish@gmail.com
job_profile    [{'title': 'Team Lead', 'role': 'Developer'}]

In [60]:
pd.read_json(data,orient='columns')

employee_name            email                                  job_profile
0         Krish  Krish@gmail.com  {'title': 'Team Lead', 'role': 'Developer'}

In [61]:
df = pd.DataFrame([['a', 'b'], ['c', 'd']],
                  index=['row 1', 'row 2'],
                  columns=['col 1', 'col 2'])

In [62]:
df

col 1 col 2
row 1     a     b
row 2     c     d

In [65]:
df.to_json()

'{"col 1":{"row 1":"a","row 2":"c"},"col 2":{"row 1":"b","row 2":"d"}}'

In [66]:
df.to_json(orient="records")

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [67]:
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1480  
3    2.93   735  
4    2.85  1450  
..    ...   ...  
172  1.74   740  
173  1.56   750  
174  1.56   835  
175  1.62   840  
176  1.60   560  

[177 rows x 14 columns]

In [69]:
pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

0      1     2     3     4    5     6     7     8     9      10    11  \
0     1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1     1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2     1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3     1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4     1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..   ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173   3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174   3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175   3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176   3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177   3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

       12    13  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [70]:
df.to_json(orient="index")

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'